version: 0.0
os: linux
files:
  - source: /
    destination: /ec2-user/EduCore/backend

hooks:
  BeforeInstall:
    - location: Script/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: Script/start_server.sh
      timeout: 300
      runas: ubuntu
