version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Entering backend directory"
      - cd backend
      - echo "Checking lock file..."
      - |
        if [ ! -f package-lock.json ]; then
          echo "package-lock.json not found, running npm install"
          npm install
        else
          npm ci
        fi

  build:
    commands:
      - npm run build
      - echo "Backend build completed"

artifacts:
  files:
    - '**/*'
  discard-paths: no
