version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - cd backend
      - npm ci

  build:
    commands:
      - npx prisma generate
      - npm run build
