name: Backend CI

on:
  push:
    branches: [ "main", "develop", "feature" ]
  pull_request:
    branches: [ "main", "develop", "feature" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'npm'

      - name: Check Node version
        run: node -v

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci
        
      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate
